/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_example_startble_console_JNI */

#ifndef _Included_com_example_startble_console_JNI
#define _Included_com_example_startble_console_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_startble_console_JNI
 * Method:    call
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_com_example_startble_console_JNI_call
  (JNIEnv *, jobject);

/*
 * Class:     com_example_startble_console_JNI
 * Method:    printLogo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_startble_console_JNI_printLogo
  (JNIEnv *, jobject);

/*
 * Class:     com_example_startble_console_JNI
 * Method:    printMenu
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_startble_console_JNI_printMenu
  (JNIEnv *, jobject);

/*
 * Class:     com_example_startble_console_JNI
 * Method:    newGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_startble_console_JNI_newGame
  (JNIEnv *, jobject);

/*
 * Class:     com_example_startble_console_JNI
 * Method:    saveGame
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_startble_console_JNI_saveGame
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_startble_console_JNI
 * Method:    loadGame
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_startble_console_JNI_loadGame
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_startble_console_JNI
 * Method:    undoMove
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_startble_console_JNI_undoMove
  (JNIEnv *, jobject);

/*
 * Class:     com_example_startble_console_JNI
 * Method:    movePiece
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jboolean JNICALL Java_com_example_startble_console_JNI_movePiece
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_startble_console_JNI
 * Method:    printSituation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_startble_console_JNI_printSituation
  (JNIEnv *, jobject);

/*
 * Class:     com_example_startble_console_JNI
 * Method:    printBoard
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_startble_console_JNI_printBoard
  (JNIEnv *, jobject);

/*
 * Class:     com_example_startble_console_JNI
 * Method:    initController
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_startble_console_JNI_initController
(JNIEnv *env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
